"use client";

/**
 * AgenticWalletTab — the dashboard "Agent" tab top-level container.
 *
 * Loads the caller's Agentic Wallet via GET /api/wallet/agentic (auth via
 * the session nonce already in sessionStorage). Shows a hero + create
 * button when no wallet exists yet; switches to the wallet card after
 * creation.
 *
 * Phase 1 MVP: single wallet per user, BNB-chain send only. Deposit
 * detection cron + multichain send unlock in Phase 2.
 */

import { useCallback, useEffect, useState } from "react";
import { getAuthCreds, clearAuthCache } from "@/app/lib/auth-client";
import { AgenticWalletCard } from "./AgenticWalletCard";

export interface AgenticWalletPublic {
  ownerAddr: string;
  address: string;
  createdAt: number;
  deletedAt: number | null;
  dailyLimitUsd: number | null;
  perTxMaxUsd: number | null;
  erc8004AgentId: string | null;
}

interface Props {
  address: string;
  signMessage: (message: string) => Promise<string | null>;
}

export function AgenticWalletTab({ address, signMessage }: Props) {
  const [wallet, setWallet] = useState<AgenticWalletPublic | null | undefined>(undefined);
  const [error, setError] = useState<string | null>(null);
  const [creating, setCreating] = useState(false);

  const reload = useCallback(async () => {
    setError(null);
    const auth = await getAuthCreds(address, signMessage);
    if (!auth) {
      setError("Please sign the auth challenge to load your Agentic Wallet.");
      setWallet(null);
      return;
    }
    const qs = new URLSearchParams({ address, nonce: auth.nonce, sig: auth.signature }).toString();
    try {
      const res = await fetch(`/api/wallet/agentic?${qs}`);
      const data = await res.json();
      if (res.status === 401 && data.code === "NONCE_EXPIRED") {
        clearAuthCache(address);
        setError("Session expired — sign in again to refresh.");
        setWallet(null);
        return;
      }
      if (!res.ok) {
        setError(data.error ?? "Failed to load Agentic Wallet.");
        setWallet(null);
        return;
      }
      setWallet(data.wallet ?? null);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setWallet(null);
    }
  }, [address, signMessage]);

  useEffect(() => {
    void reload();
  }, [reload]);

  const create = useCallback(async () => {
    setCreating(true);
    setError(null);
    try {
      const auth = await getAuthCreds(address, signMessage);
      if (!auth) {
        setError("Please sign the auth challenge to create a wallet.");
        return;
      }
      const res = await fetch("/api/wallet/agentic", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ address, nonce: auth.nonce, signature: auth.signature }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.message ?? data.error ?? "Failed to create wallet.");
        return;
      }
      setWallet(data.wallet);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setCreating(false);
    }
  }, [address, signMessage]);

  return (
    <div className="space-y-5">
      <div className="space-y-1 mb-2">
        <h2 className="text-lg font-semibold">Your Agentic Wallet</h2>
        <p className="text-white/40 text-sm">
          A dedicated wallet generated by Q402 for gasless USDC / USDT payments. Your
          MetaMask / OKX EOA is never delegated. Deposit stablecoins here once; your AI
          (or you) sends from it gaslessly across BNB chain. Multichain unlocks with a
          paid subscription.
        </p>
      </div>

      {error && (
        <div className="rounded-lg border border-red-500/30 bg-red-500/5 px-4 py-3 text-sm text-red-200/80">
          {error}
        </div>
      )}

      {wallet === undefined && (
        <div className="text-white/40 text-sm">Loading…</div>
      )}

      {wallet === null && (
        <div
          className="rounded-2xl border p-6 flex flex-col items-start gap-4"
          style={{ background: "#0F1929", borderColor: "rgba(255,255,255,0.07)" }}
        >
          <div className="space-y-1">
            <div className="text-white font-semibold">Get your first Agentic Wallet</div>
            <div className="text-white/50 text-sm max-w-xl">
              One click. Your wallet is generated server-side and held under AES-256-GCM
              encryption. Export the private key anytime; nothing about Q402&apos;s normal
              gasless flow changes.
            </div>
          </div>
          <button
            type="button"
            onClick={create}
            disabled={creating}
            className="px-4 py-2 rounded-md text-sm font-semibold bg-yellow text-navy hover:bg-yellow/90 disabled:opacity-50"
          >
            {creating ? "Creating…" : "Create Agentic Wallet"}
          </button>
        </div>
      )}

      {wallet && (
        <AgenticWalletCard
          wallet={wallet}
          address={address}
          signMessage={signMessage}
          onChanged={() => void reload()}
        />
      )}
    </div>
  );
}
